default: &default
  name: Crystal [ANN]
  description: Announce new project, blog post, version update or any other Crystal work

development:
  <<: *default
  url: http://localhost:3008

staging:
  <<: *default
  url: https://crystal-ann-staging.herokuapp.com

production:
  <<: *default
  url: https://crystal-ann.com
